[package]
name = "stunnel"
version = "0.1.0"
edition = "2021"
authors = ["Govin Liu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.4", features = ["derive"]}